from typing import Protocol
from uuid import UUID

from decision_os.domain.action import Action, ActionExecution


class ActionRepository(Protocol):
    def get(self, action_id: UUID, tenant_id: UUID) -> Action | None: ...
    def add(self, action: Action) -> None: ...
    def save(self, action: Action) -> None: ...


class ActionExecutionRepository(Protocol):
    def get_latest_for_action(self, action_id: UUID) -> ActionExecution | None: ...
    def add(self, execution: ActionExecution) -> None: ...
