from typing import Protocol
from uuid import UUID

from decision_os.domain.outcome import ActualOutcome, ExpectedOutcome, Verification


class ExpectedOutcomeRepository(Protocol):
    def get(self, outcome_id: UUID, tenant_id: UUID) -> ExpectedOutcome | None: ...
    def add(self, outcome: ExpectedOutcome) -> None: ...


class ActualOutcomeRepository(Protocol):
    def get(self, outcome_id: UUID, tenant_id: UUID) -> ActualOutcome | None: ...
    def add(self, outcome: ActualOutcome) -> None: ...
    def save(self, outcome: ActualOutcome) -> None: ...


class VerificationRepository(Protocol):
    def get(self, verification_id: UUID, tenant_id: UUID) -> Verification | None: ...
    def add(self, verification: Verification) -> None: ...
    def save(self, verification: Verification) -> None: ...
